import React from 'react';
import CircularProbability from './CircularProbability';
import Disclaimer from './Disclaimer';
import { Activity, CheckCircle, AlertTriangle, User, ShieldAlert, Stethoscope, RefreshCw } from 'lucide-react';
import '../styles/result.css';

const PredictionResult = ({ result, formData, onReset }) => {
  const isPositive = result.prediction === 1;
  const label = result.predictionLabel || (isPositive ? 'Positive' : 'Negative');
  const percent = Math.round(Number(result.probability) * 100);

  // Format helper functions
  const formatGender = (val) => (Number(val) === 1 ? 'Male' : 'Female');
  const formatBool = (val) => (Number(val) === 1 ? 'Yes' : 'No');

  return (
    <div className="result-card-3d perspective-container">
      {/* Classification Tag Header */}
      <div className={`result-status-badge ${isPositive ? 'positive' : 'negative'}`}>
        {isPositive ? <AlertTriangle size={22} /> : <CheckCircle size={22} />}
        <span>
          Prediction Result — Prediction: {label} | Probability: {percent}%
        </span>
      </div>

      {/* 3D Circular Probability Progress Ring */}
      <CircularProbability probability={result.probability} />

      {/* Research & Educational Disclaimer */}
      <Disclaimer text="This result is generated by a machine-learning statistical model and is not a medical diagnosis. Consult a qualified healthcare professional for proper medical evaluation." />

      {/* Patient Feature Summary Breakdown */}
      <div className="summary-dashboard">
        <h3 className="dashboard-title">
          <Activity size={22} color="var(--racing-red)" />
          <span>Patient Feature Summary</span>
        </h3>

        <div className="summary-sections-grid">
          {/* Card 1: Patient Summary */}
          <div className="summary-card">
            <div className="summary-card-header">
              <User size={18} />
              <span>Patient Summary</span>
            </div>
            <div className="summary-item-list">
              <div className="summary-item">
                <span className="summary-item-key">Age</span>
                <span className="summary-item-val">{formData.Age} yrs</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Gender</span>
                <span className="summary-item-val">{formatGender(formData.Gender)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">BMI</span>
                <span className="summary-item-val">{formData.BMI}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">UPDRS Score</span>
                <span className="summary-item-val">{formData.UPDRS}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">MoCA Score</span>
                <span className="summary-item-val">{formData.MoCA}</span>
              </div>
            </div>
          </div>

          {/* Card 2: Clinical Factors */}
          <div className="summary-card">
            <div className="summary-card-header">
              <ShieldAlert size={18} />
              <span>Clinical Factors</span>
            </div>
            <div className="summary-item-list">
              <div className="summary-item">
                <span className="summary-item-key">Hypertension</span>
                <span className="summary-item-val">{formatBool(formData.Hypertension)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Diabetes</span>
                <span className="summary-item-val">{formatBool(formData.Diabetes)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Stroke History</span>
                <span className="summary-item-val">{formatBool(formData.Stroke)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Depression</span>
                <span className="summary-item-val">{formatBool(formData.Depression)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Family History</span>
                <span className="summary-item-val">{formatBool(formData.FamilyHistoryParkinsons)}</span>
              </div>
            </div>
          </div>

          {/* Card 3: Symptoms Breakdown */}
          <div className="summary-card">
            <div className="summary-card-header">
              <Stethoscope size={18} />
              <span>Symptoms Breakdown</span>
            </div>
            <div className="summary-item-list">
              <div className="summary-item">
                <span className="summary-item-key">Tremor</span>
                <span className="summary-item-val">{formatBool(formData.Tremor)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Rigidity</span>
                <span className="summary-item-val">{formatBool(formData.Rigidity)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Bradykinesia</span>
                <span className="summary-item-val">{formatBool(formData.Bradykinesia)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Posture</span>
                <span className="summary-item-val">{formatBool(formData.Posture)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Speech Problems</span>
                <span className="summary-item-val">{formatBool(formData.SpeechProblems)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Sleep Disorders</span>
                <span className="summary-item-val">{formatBool(formData.SleepDisorders)}</span>
              </div>
              <div className="summary-item">
                <span className="summary-item-key">Constipation</span>
                <span className="summary-item-val">{formatBool(formData.Constipation)}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Reset / New Assessment Action */}
      <button onClick={onReset} className="btn-primary" style={{ marginTop: '1rem' }}>
        <RefreshCw size={18} />
        <span>Run Another Assessment</span>
      </button>
    </div>
  );
};

export default PredictionResult;
